[features]
seeds = false
skip-lint = false

[programs.localnet]
leash = "EZQjF3NwVTMUrRdDiCwzuabFEoe2viVfFhEaWPkj6gkV"
separatrix_program = "CsnV36BSJsfCRSrJQSCddi5ZM7XAA8KVpL8ziCh7xSzp"

[programs.devnet]
leash = "EZQjF3NwVTMUrRdDiCwzuabFEoe2viVfFhEaWPkj6gkV"
separatrix_program = "CsnV36BSJsfCRSrJQSCddi5ZM7XAA8KVpL8ziCh7xSzp"

[provider]
cluster = "Devnet"
wallet = "keys/owner-devnet.json"

[scripts]
test = "npm run test:anchor"
