#!/usr/bin/env python3
r"""Run a compiled pytket circuit on Quantinuum's Selene emulator, via Guppy.

Why this file exists at all
---------------------------
Selene is the emulator Phase 1 of the SG Grand Challenge runs on, and it is the
only local tool that models the Helios *runtime* (and, uniquely, ion leakage and
seepage). It does not eat pytket circuits. Its documented inputs are HUGR — i.e.
Guppy — and QIR.

The QIR route was tried first and does not work with the versions installed
here: ``pytket.qir.pytket_to_qir`` emits ``__quantum__qis__read_result__body``,
and Selene's QIR validator (``qir-qis`` 0.1.10) rejects that symbol with
``Unsupported QIR QIS function``. That is true for every profile pytket-qir 2.0
offers (BASE, ADAPTIVE, PYTKET). So this module takes the other documented
route: it emits Guppy source for the circuit, in the Helios native gate set,
and lets Guppy compile it to HUGR.

The emission is a straight-line transliteration, which is exactly why it needs
checking rather than trusting: :func:`sampling_check` compares the emitted
program's sampled distribution against the exact statevector distribution of
the circuit it came from, and compares that discrepancy against the
shot-noise-only null obtained by sampling the exact distribution directly. A
transliteration bug shows up there; a correct one is indistinguishable from
shot noise.

Readout uses ``measure_leaked`` rather than ``measure`` throughout. It returns
a three-valued result (0, 1, leaked), so every shot separates two things that
prior art conflates:

* the **in-constraint probability** — did the surviving computational state
  still have Hamming weight k;
* the **physical leakage** — did an ion leave the computational manifold at
  all (Wood & Gambetta, PRA 97, 032306).

Conventions
-----------
Both pytket parameters and Guppy's ``angle`` are in **half-turns**, so the
parameters pass through unscaled. This is worth stating because it is the one
thing that was wrong first time and it fails silently: ``angle``'s docstring
notes that ``float(angle)`` converts to radians by multiplying by pi, which
reads like a radian constructor and is not one. The emission self-check below
caught it (TVD ratio 8.8 instead of ~1); nothing else would have.

Qubit ``q_j`` in the emitted program is the j-th qubit of the circuit in
pytket's own ordering, so the j-th ``"m"`` result is bit j of the big-endian
statevector index — the same convention as
:func:`quantum.dicke_xy.tket_statevector`.
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from quantum.dicke_xy import HELIOS, HeliosSpec

__all__ = [
    "SeleneUnavailable",
    "EmissionError",
    "selene_status",
    "emit_guppy_source",
    "SeleneProgram",
    "build_program",
    "SeleneRun",
    "run_program",
    "error_model_catalogue",
    "sampling_check",
]


class SeleneUnavailable(RuntimeError):
    """Selene, Guppy or a required compiler is not installed."""


class EmissionError(RuntimeError):
    """The circuit contains something the Guppy emitter cannot express."""


_GUPPY_PREAMBLE = """\
# Generated by quantum/selene_backend.py. Do not edit.
# Straight-line Guppy transliteration of a pytket circuit already rebased to the
# Helios native gate set {PhasedX, Rz, ZZPhase}. Guppy's `angle` and pytket's
# gate parameters are both in half-turns, so parameters pass through unscaled.
from guppylang import guppy
from guppylang.std.quantum import qubit
from guppylang.std.qsystem import phased_x, rz, zz_phase, measure_leaked
from guppylang.std.angles import angle
from guppylang.std.builtins import result


@guppy
def main() -> None:
"""


def selene_status() -> tuple[bool, str]:
    """``(available, explanation)`` — never raises, so callers can report it."""
    missing: list[str] = []
    for module in ("guppylang", "selene_sim", "selene_hugr_qis_compiler"):
        if importlib.util.find_spec(module) is None:
            missing.append(module)
    if missing:
        return False, "missing module(s): " + ", ".join(missing)
    try:
        import selene_sim  # noqa: F401
        from importlib.metadata import version

        return True, (
            f"selene-sim {version('selene-sim')}, guppylang {version('guppylang')}"
        )
    except Exception as exc:  # noqa: BLE001 - report, do not crash the sweep
        return False, f"{type(exc).__name__}: {exc}"


def emit_guppy_source(circuit) -> tuple[str, list[int]]:
    """Transliterate a Helios-native pytket circuit into Guppy source.

    Returns ``(source, qubit_order)`` where ``qubit_order`` lists the pytket
    qubit indices in the order they are declared and measured.

    Raises :class:`EmissionError` on any gate outside {PhasedX, Rz, ZZPhase},
    on a symbolic parameter, or on a mid-circuit measurement — rather than
    silently dropping it, which is how an emitter quietly starts lying.
    """
    commands = [c for c in circuit.get_commands() if c.op.type.name != "Barrier"]
    indices = sorted({q.index[0] for c in commands for q in c.qubits})
    for qubit_obj in circuit.qubits:
        idx = qubit_obj.index[0]
        if idx not in indices:
            indices.append(idx)
    indices = sorted(indices)
    position = {idx: pos for pos, idx in enumerate(indices)}

    lines: list[str] = []
    for pos in range(len(indices)):
        lines.append(f"    q{pos} = qubit()")

    for command in commands:
        name = command.op.type.name
        try:
            params = [float(p) for p in command.op.params]
        except (TypeError, ValueError) as exc:
            raise EmissionError(
                f"symbolic parameter in {name}; bind parameters before emission"
            ) from exc
        qubits = [position[q.index[0]] for q in command.qubits]
        if name == "PhasedX":
            lines.append(
                f"    phased_x(q{qubits[0]}, angle({params[0]!r}), "
                f"angle({params[1]!r}))"
            )
        elif name == "Rz":
            lines.append(f"    rz(q{qubits[0]}, angle({params[0]!r}))")
        elif name == "ZZPhase":
            lines.append(
                f"    zz_phase(q{qubits[0]}, q{qubits[1]}, angle({params[0]!r}))"
            )
        else:
            raise EmissionError(
                f"gate {name!r} is not in the Helios native set "
                "{PhasedX, Rz, ZZPhase}; rebase before emission"
            )

    # Leakage-aware destructive readout, in declaration order. `to_result()`
    # returns nothing when the ion has left the computational manifold; that
    # shot is recorded as leaked and its bit is reported as 0 so the caller can
    # still form a bitstring, but the leak flag is what should be used.
    for pos in range(len(indices)):
        lines.extend(
            [
                f"    m{pos} = measure_leaked(q{pos})",
                f'    result("leak", m{pos}.is_leaked())',
                f"    o{pos} = m{pos}.to_result()",
                f"    if o{pos}.is_some():",
                f'        result("m", o{pos}.unwrap())',
                "    else:",
                f"        o{pos}.unwrap_nothing()",
                '        result("m", False)',
            ]
        )
    return _GUPPY_PREAMBLE + "\n".join(lines) + "\n", indices


@dataclass(slots=True)
class SeleneProgram:
    """A built Selene executable plus the provenance needed to report it."""

    instance: Any
    n_qubits: int
    qubit_order: list[int]
    source_path: Path
    build_seconds: float
    gate_count: int


def build_program(
    circuit, name: str | None = None, build_root: Path | None = None
) -> SeleneProgram:
    """Emit, type-check and compile a circuit into a Selene executable.

    Guppy is a linearly typed language, so a qubit that is used after being
    consumed, or never measured, is a *compile* error rather than a wrong
    answer. That property is doing real work here: it is the reason a
    machine-generated program of a few hundred straight-line gates can be
    trusted to have consumed every qubit exactly once.
    """
    available, detail = selene_status()
    if not available:
        raise SeleneUnavailable(detail)
    import selene_sim as selene

    source, order = emit_guppy_source(circuit)
    root = Path(build_root or tempfile.mkdtemp(prefix="selene-dicke-"))
    root.mkdir(parents=True, exist_ok=True)
    module_name = f"dicke_guppy_{uuid.uuid4().hex[:12]}"
    source_path = root / f"{module_name}.py"
    source_path.write_text(source, encoding="utf-8")

    started = time.time()
    spec = importlib.util.spec_from_file_location(module_name, source_path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise SeleneUnavailable(f"could not load generated module {source_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    instance = selene.build(
        module.main.compile(), name=name or module_name, build_dir=root / "build"
    )
    return SeleneProgram(
        instance=instance,
        n_qubits=len(order),
        qubit_order=order,
        source_path=source_path,
        build_seconds=time.time() - started,
        gate_count=len([c for c in circuit.get_commands() if c.op.type.name != "Barrier"]),
    )


@dataclass(slots=True)
class SeleneRun:
    """One emulator run. Every field here is measured, not estimated."""

    error_model: str
    error_model_params: dict[str, float]
    shots: int
    bitstrings: list[tuple[int, ...]] = field(default_factory=list)
    leak_flags: list[tuple[int, ...]] = field(default_factory=list)
    wall_seconds: float = 0.0

    @property
    def shots_with_leakage(self) -> int:
        return sum(1 for flags in self.leak_flags if any(flags))

    def in_constraint_split(self, k: int) -> dict[str, Any]:
        """Separate sector loss from physical leakage, shot by shot.

        Prior art reports one number, the feasible fraction, which silently
        merges two different failures. Here a shot is out of constraint either
        because an ion left the computational manifold — visible in the leak
        flag — or because computational-space error moved the register to a
        different Hamming weight. ``in_constraint_probability_leak_free`` is the
        second effect with the first removed, and is the quantity a
        symmetry-verification scheme could actually act on.
        """
        leak_free = [
            bits for bits, flags in zip(self.bitstrings, self.leak_flags) if not any(flags)
        ]
        in_constraint = sum(1 for bits in self.bitstrings if sum(bits) == k)
        in_constraint_leak_free = sum(1 for bits in leak_free if sum(bits) == k)
        return {
            "shots": self.shots,
            "in_constraint_shots": in_constraint,
            "in_constraint_probability": in_constraint / self.shots if self.shots else 0.0,
            "leak_free_shots": len(leak_free),
            "physical_leakage_probability": self.shots_with_leakage / self.shots
            if self.shots
            else 0.0,
            "in_constraint_probability_leak_free": (
                in_constraint_leak_free / len(leak_free) if leak_free else None
            ),
        }

    def counts(self) -> dict[tuple[int, ...], int]:
        out: dict[tuple[int, ...], int] = {}
        for bits in self.bitstrings:
            out[bits] = out.get(bits, 0) + 1
        return out

    def empirical_distribution(self, n: int) -> np.ndarray:
        """Distribution over the 2^n basis states, in big-endian index order."""
        probabilities = np.zeros(1 << n, dtype=float)
        for bits in self.bitstrings:
            index = 0
            for bit in bits:
                index = (index << 1) | int(bit)
            probabilities[index] += 1.0
        total = probabilities.sum()
        return probabilities / total if total else probabilities


def error_model_catalogue(spec: HeliosSpec = HELIOS) -> dict[str, dict[str, Any]]:
    """The error models available *locally*, with their provenance spelled out.

    The calibrated Helios model (``QSystemErrorModel``) is not in the
    open-source package — the locally installed ``selene_sim`` exports only
    Ideal, Depolarizing and SimpleLeakage, and the ``HeliosErrorParams`` schema
    that ships with ``quantinuum_schemas`` has ``None`` for all 33 of its
    defaults. So the depolarizing arm below is parameterised from *published
    spec-sheet infidelities*, not from a calibration snapshot, and every number
    it produces is labelled accordingly.
    """
    return {
        "ideal": {
            "factory": "IdealErrorModel",
            "params": {},
            "provenance": "noiseless; used as the emission self-check control",
        },
        "helios_spec_depolarizing": {
            "factory": "DepolarizingErrorModel",
            "params": {
                "p_1q": spec.one_qubit_infidelity,
                "p_2q": spec.two_qubit_infidelity,
                "p_meas": spec.spam_infidelity,
                "p_init": spec.spam_infidelity,
            },
            "provenance": (
                "hand-parameterised stand-in: depolarizing rates set to the "
                "published Helios infidelities (1q 2.5e-5, 2q 7.9e-4, SPAM "
                "3.3e-4). NOT Quantinuum's calibrated QSystemErrorModel, which "
                "is only reachable through Nexus."
            ),
        },
        "leakage_only": {
            "factory": "SimpleLeakageErrorModel",
            "params": {"p_leak": spec.two_qubit_infidelity},
            "provenance": (
                "physical leakage channel in isolation, with every other channel "
                "switched off. The rate is a deliberate UPPER-BOUND STRESS "
                "SETTING, not an estimate of Helios: it charges the entire "
                "published two-qubit infidelity (7.9e-4) to leakage, whereas on "
                "real hardware leakage is a fraction of that. Quantinuum does not "
                "publish a Helios leakage rate. The purpose is to demonstrate and "
                "bound the decomposition — ions leaving the computational "
                "manifold versus computational-space error that merely leaves the "
                "weight-k sector — not to predict a device number."
            ),
        },
    }


def _instantiate(factory: str, params: dict[str, Any], seed: int):
    import selene_sim as selene

    return getattr(selene, factory)(random_seed=seed, **params)


def run_program(
    program: SeleneProgram,
    shots: int,
    model_name: str,
    spec: HeliosSpec = HELIOS,
    seed: int = 20260817,
    timeout_seconds: float | None = None,
) -> SeleneRun:
    """Run ``shots`` trajectories under a named error model.

    Note the ``[list(shot) for shot in ...]``: ``run_shots`` returns nested
    iterators and the inner ones must be fully drained. Materialising only the
    outer iterator makes the Rust child process abort and surfaces as a
    ``ConnectionRefused`` OS error that points nowhere near the real cause.
    """
    import selene_sim as selene

    catalogue = error_model_catalogue(spec)
    if model_name not in catalogue:
        raise KeyError(f"unknown error model {model_name!r}")
    entry = catalogue[model_name]
    model = _instantiate(entry["factory"], entry["params"], seed)

    started = time.time()
    raw = [
        list(shot)
        for shot in program.instance.run_shots(
            simulator=selene.Quest(),
            error_model=model,
            n_qubits=program.n_qubits,
            n_shots=shots,
            random_seed=seed,
            timeout=timeout_seconds,
        )
    ]
    elapsed = time.time() - started

    run = SeleneRun(
        error_model=model_name,
        error_model_params={k: float(v) for k, v in entry["params"].items()},
        shots=len(raw),
        wall_seconds=elapsed,
    )
    for shot in raw:
        bits = tuple(int(value) for tag, value in shot if tag == "m")
        leaks = tuple(int(value) for tag, value in shot if tag == "leak")
        if len(bits) != program.n_qubits or len(leaks) != program.n_qubits:
            raise RuntimeError(
                f"shot returned {len(bits)} bits and {len(leaks)} leak flags for "
                f"{program.n_qubits} qubits; the emitted program and the parser "
                "disagree"
            )
        run.bitstrings.append(bits)
        run.leak_flags.append(leaks)
    return run


def sampling_check(
    run: SeleneRun, exact_probabilities: np.ndarray, n: int, seed: int = 20260817
) -> dict[str, float | None]:
    """Is the emitted program's output distribution the circuit's distribution?

    Compares the total variation distance between the emulator's samples and
    the exact statevector distribution against a **null** built by drawing the
    same number of samples from the exact distribution directly. With a correct
    emission the two are the same quantity up to Monte Carlo fluctuation, so
    ``ratio`` sits near 1. A transliteration bug — a dropped gate, a factor of
    pi, a swapped qubit — moves it far above 1.

    Only meaningful for the noiseless (``ideal``) run; under a noise model the
    distributions differ *because of the physics*, which is the thing being
    measured.
    """
    observed = run.empirical_distribution(n)
    exact = np.asarray(exact_probabilities, dtype=float)
    rng = np.random.default_rng(seed)
    draws = rng.multinomial(run.shots, exact / exact.sum())
    null = draws / max(run.shots, 1)
    tvd = float(0.5 * np.abs(observed - exact).sum())
    tvd_null = float(0.5 * np.abs(null - exact).sum())
    return {
        "tvd_vs_exact": tvd,
        "tvd_shot_noise_null": tvd_null,
        # None rather than inf: the caller serialises this to JSON with
        # allow_nan=False, and a non-finite value there would take down a
        # finished sweep at the write step.
        "ratio": float(tvd / tvd_null) if tvd_null > 0 else None,
    }
